language: objective-c
sudo: required
before_install:
  # - openssl aes-256-cbc -K $encrypted_b355b4971651_key -iv $encrypted_b355b4971651_iv -in ios_distribution.cer.enc -out ./TestRock/RockCer/ios_distribution.cer -d
  - DevToolsSecurity -status
  - DevToolsSecurity -enable
install: 
  - cd HipRock
  - npm install 
before_script:
  - chmod +x ./ios/RockCer/add-key.sh
  - cd ./ios/RockCer
  - ./add-key.sh
  - cd -
script:
  - chmod +x ./buildTestIpa.sh
  - ./buildTestIpa.sh
 