language: objective-c

before_install:
  # - openssl aes-256-cbc -K $encrypted_b355b4971651_key -iv $encrypted_b355b4971651_iv -in ios_distribution.cer.enc -out ./TestRock/RockCer/ios_distribution.cer -d
  - DevToolsSecurity -status
  - DevToolsSecurity -enable
install: 
  # npm install 
before_script:
  - cd AutoBuildTravisCi
  - chmod +x ./TestRock/RockCer/add-key.sh
  - cd ./TestRock/RockCer
  - ./add-key.sh
  - cd -
script:
  - xcodebuild -project "./TestRock/TestRock.xcodeproj" -scheme "TestRock" archive -archivePath "./buildTemp/TestRock_Test_V.xcarchive" -quiet
  - xcodebuild -exportArchive -archivePath "./buildTemp/TestRock_Test_V.xcarchive" -exportPath "./buildTemp/TestRock_Test_V" -exportOptionsPlist "exportTestOptions.plist" -quiet
  - cd ./buildTemp && ls -R | grep ipa
  # - curl -F "file=@TestRock_Test_V/TestRock.ipa" -F "uKey= 24af41e3b5e5117e773a733378aefa29" -F "_api_key= 0691c7489e57a5158796f6e1e7e988bd" -F "installType=2" -F "password=123456" -F "updateDescription=$description" http://qiniu-storage.pgyer.com/apiv1/app/upload
  - curl -F 'file=@TestRock_Test_V/TestRock.ipa' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
