language: objective-c
sudo: required
android:
  components:
  - build-tools-23.0.1
  - build-tools-23.0.2
  - build-tools-26.0.1
  - build-tools-26.0.2 
  - android-23
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
cache:
  directories:
  - node_modules
before_install:
  # - openssl aes-256-cbc -K $encrypted_b355b4971651_key -iv $encrypted_b355b4971651_iv -in ios_distribution.cer.enc -out ./TestRock/RockCer/ios_distribution.cer -d
  - DevToolsSecurity -status
  - DevToolsSecurity -enable

  - nvm install 6
  - node --version
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
  - chmod +x android-ndk-r10e-darwin-x86_64.bin
  - ./android-ndk-r10e-darwin-x86_64.bin 
  - export ANDROID_NDK=`pwd`/android-ndk-r10e
  - echo $ANDROID_NDK
install: 
  - cd HipRock
  - npm install 
  - sed -ig '237,240d' node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.m
  - cat
before_script:
  - chmod +x ./ios/RockCer/add-key.sh
  - cd ./ios/RockCer
  - ./add-key.sh
  - cd -
script:
  - chmod +x ./buildTestIpa.sh
  - ./buildTestIpa.sh

  - cd android 
  - ./gradlew assembleRelease
  - ROCK_VERSION=`awk -F= '/ROCK_VERSION/{print $2}' android/gradle.properties |tail -n 1`
  - curl -F "file=@app-internal-release-$ROCK_VERSION.apk" -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
