language: objective-c
sudo: required
before_install:
  # - openssl aes-256-cbc -K $encrypted_b355b4971651_key -iv $encrypted_b355b4971651_iv -in ios_distribution.cer.enc -out ./TestRock/RockCer/ios_distribution.cer -d
  - DevToolsSecurity -status
  - DevToolsSecurity -enable
install: 
  - cd learnRN
  - npm install 
before_script:
  - chmod +x ./ios/RockCer/add-key.sh
  - cd ./ios/RockCer
  - ./add-key.sh
  - cd -
script:
  - xcodebuild -project "./ios/learnRN.xcodeproj" -scheme "learnRN" archive -archivePath "./buildIOSTemp/learnRNV1.0.0.xcarchive" -quiet
  - xcodebuild -exportArchive -archivePath "./buildIOSTemp/learnRNV1.0.0.xcarchive" -exportPath "./buildIOSTemp/learnRNV1.0.0" -exportOptionsPlist "exportTestOptions.plist" -quiet
  - cd ./buildIOSTemp && ls -R | grep ipa
  - curl -F 'file=@learnRN_0.0.1/Apps/learnRN.ipa' -F 'uKey=7d42c69844b88157360fe2dc141fdf1a' -F '_api_key=be1290e71bb2fab7a9547cda2ee37d7b' 'https://www.pgyer.com/apiv1/app/upload'
